[project]
name = "whisperxgui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyside6>=6.10.0",
    "whisperx>=3.7.4",
]
